### ISSUE TITLE
nil pointer exception on `utils.IsfileExists`

### ISSUE THREAD

**Issue by cainelli** [aws/aws-ebpf-sdk-go#71]
The [aws-network-policy-agent](https://github.com/aws/aws-network-policy-agent) crashes with the following stack trace:

```
kubectl describe daemonset aws-node -n kube-system | grep Image | cut -d "/" -f 2-3
amazon-k8s-cni-init:v1.16.0
amazon-k8s-cni:v1.16.0
amazon/aws-network-policy-agent:v1.0.7
```

```
{"level":"info","ts":"2024-01-03T13:20:51.896Z","caller":"runtime/asm_amd64.s:1650","msg":"version","GitVersion":"","GitCommit":"","BuildDate":""}
2024-01-03 13:20:51.940151872 +0000 UTC Logger.check error: failed to get caller
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x563fbf770276]

goroutine 180 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x563fc12d5be0?, 0x563fc273a3e0?})
	/root/sdk/go1.21.3/src/runtime/panic.go:914 +0x21f
github.com/aws/aws-ebpf-sdk-go/pkg/utils.IsfileExists({0xc000558070?, 0x0?})
	/go/pkg/mod/github.com/aws/aws-ebpf-sdk-go@v1.0.4/pkg/utils/utils.go:90 +0x56
github.com/aws/aws-ebpf-sdk-go/pkg/maps.(*BpfMap).PinMap(0xc001070c58, {0xc000558070, 0x66}, 0x5d3f30?)
	/go/pkg/mod/github.com/aws/aws-ebpf-sdk-go@v1.0.4/pkg/maps/loader.go:232 +0x56
github.com/aws/aws-ebpf-sdk-go/pkg/maps.(*BpfMap).CreateBPFMap(0x1?, {0xb, 0x8, 0x120, 0x10000, 0x1, 0x0, 0xc0000132c0, 0x0, {0xc000f5b750, ...}})
	/go/pkg/mod/github.com/aws/aws-ebpf-sdk-go@v1.0.4/pkg/maps/loader.go:219 +0x57c
github.com/aws/aws-ebpf-sdk-go/pkg/elfparser.(*elfLoader).loadMap(0xc0010711f8, {0xc00011d380, 0x1, 0xc000683380?})
	/go/pkg/mod/github.com/aws/aws-ebpf-sdk-go@v1.0.4/pkg/elfparser/elf.go:165 +0x27d
github.com/aws/aws-ebpf-sdk-go/pkg/elfparser.(*elfLoader).doLoadELF(0xc0010711f8)
	/go/pkg/mod/github.com/aws/aws-ebpf-sdk-go@v1.0.4/pkg/elfparser/elf.go:600 +0x65
github.com/aws/aws-ebpf-sdk-go/pkg/elfparser.(*bpfSDKClient).LoadBpfFile(0xc0004f2640, {0x563fc0627796?, 0xc00055b400?}, {0xc00012c1c0, 0x3d})
	/go/pkg/mod/github.com/aws/aws-ebpf-sdk-go@v1.0.4/pkg/elfparser/elf.go:140 +0x1d9
github.com/aws/aws-network-policy-agent/pkg/ebpf.(*bpfClient).loadBPFProgram(0xc0000f3600, {0x563fc0627796, 0x12}, {0x563fc0617881, 0x7}, {0xc00012c1c0, 0x3d})
	/workspace/pkg/ebpf/bpf_client.go:619 +0xef
github.com/aws/aws-network-policy-agent/pkg/ebpf.(*bpfClient).attachIngressBPFProbe(0xc0000f3600, {0xc000f5b4a0, 0xe}, {0xc00012c1c0, 0x3d})
	/workspace/pkg/ebpf/bpf_client.go:504 +0x1f6
github.com/aws/aws-network-policy-agent/pkg/ebpf.(*bpfClient).AttacheBPFProbes(0xc0000f3600, {{0xc0006a0190?, 0x39?}, {0xc00046f440?, 0x9?}}, {0xc00012c1c0, 0x3d}, 0x1, 0x1)
	/workspace/pkg/ebpf/bpf_client.go:412 +0x275
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).configureeBPFProbes(0xc0001566c0, {0x563fc1662d38, 0xc00105c750}, {0xc00012c1c0, 0x3d}, {0xc000442a40?, 0x1, 0xc000041cf0?}, {0xc00011d1c0, 0x1, ...}, ...)
	/workspace/controllers/policyendpoints_controller.go:259 +0x443
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).reconcilePolicyEndpoint(0xc0001566c0, {0x563fc1662d38, 0xc00105c750}, 0xc0008fed00)
	/workspace/controllers/policyendpoints_controller.go:232 +0x7f0
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).reconcile(0xc0001566c0, {0x563fc1662d38, 0xc00105c750}, {{{0xc0006a0070, 0x9}, {0xc00010ea40, 0x1a}}})
	/workspace/controllers/policyendpoints_controller.go:149 +0x22f
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).Reconcile(0xc0001566c0, {0x563fc1662d38, 0xc00105c750}, {{{0xc0006a0070, 0x9}, {0xc00010ea40, 0x1a}}})
	/workspace/controllers/policyendpoints_controller.go:130 +0x125
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x563fc1664f08?, {0x563fc1662d38?, 0xc00105c750?}, {{{0xc0006a0070?, 0xb?}, {0xc00010ea40?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000d23c0, {0x563fc1662d70, 0xc000461450}, {0x563fc13ca580?, 0xc0004f2040?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316 +0x3c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000d23c0, {0x563fc1662d70, 0xc000461450})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 136
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:223 +0x565
```

It seems a miss error handling on

https://github.com/aws/aws-ebpf-sdk-go/blob/de654b1686d7ffa38e5a4a9d37c0e48569159b9e/pkg/utils/utils.go#L85-L91

I reproduced the issue with a custom build of `aws-network-policy-agent` and I get the following error:

```shell
Error while checking file /sys/fs/bpf/globals/aws/maps/gateway-services-ssh-proxy.ssh-healthcheck-28404890-ssh-proxy_ingress_map: stat /sys/fs/bpf/globals/aws/maps/gateway-services-ssh-proxy.ssh-healthcheck-28404890-ssh-proxy_ingress_map: operation not permitted
```

Any hint why this would happen? I'm running on latest bottle rocket and EKS.

**Comment by jayanthvn** [comment]
@cainelli - There is a .(dot) in the name and you are running into this issue - https://github.com/aws/aws-network-policy-agent/issues/118#issuecomment-1786032859

**Comment by cainelli** [comment]
aha..sorry I missed this issue. Do you have a suggestion how to handle it? at least not to crash it..I assume https://github.com/aws/aws-ebpf-sdk-go/pull/72 is not a viable approach.

**Comment by cainelli** [comment]
I did a try normalizing the identifier which _seems_ to have worked but have a feeling I'm being naive and too optimistic with the simplistic solution.

```shell
bash-4.2# ls /sys/fs/bpf/globals/aws/*
/sys/fs/bpf/globals/aws/maps:
cainelli_me-6c9d6b666-cainelli_egress_map  cainelli_me-6c9d6b666-cainelli_ingress_map  global_aws_conntrack_map  global_policy_events

/sys/fs/bpf/globals/aws/programs:
cainelli_me-6c9d6b666-cainelli_handle_egress  cainelli_me-6c9d6b666-cainelli_handle_ingress
```

Logs in `/var/log/aws-routed-eni/*`
```shell
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controller/controller.go:316","msg":"Received a new reconcile request","req":{"name":"block-egress-rk8sh","namespace":"cainelli"}}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:127","msg":"Processing Policy Endpoint  ","Name: ":"block-egress-rk8sh","Namespace ":"cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Parent NP resource:","Name: ":"block-egress"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:196","msg":"Found another PE resource for the parent NP","name":"block-egress-rk8sh"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Total PEs for Parent NP:","Count: ":1}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Derive PE Object ","Name ":"block-egress-rk8sh"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Processing PE ","Name ":"block-egress-rk8sh"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:196","msg":"Found a matching Pod: ","name: ":"cainelli.me-6c9d6b666-mcx9z","namespace: ":"cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:196","msg":"Derived ","Pod identifier: ":"cainelli_me-6c9d6b666-cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:451","msg":"Current PE Count for Parent NP:","Count: ":1}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:451","msg":"PE for parent NP","name":"block-egress-rk8sh"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Total number of PolicyEndpoint resources for","podIdentifier ":"cainelli_me-6c9d6b666-cainelli"," are ":1}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Deriving Firewall rules for PolicyEndpoint:","Name: ":"block-egress-rk8sh"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Total no.of - ","ingressRules":0,"egressRules":1}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:127","msg":"No Ingress rules and no ingress isolation - Appending catch all entry"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Processing Pod: ","name:":"cainelli.me-6c9d6b666-mcx9z","namespace:":"cainelli","podIdentifier: ":"cainelli_me-6c9d6b666-cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:228","msg":"Pod already has Ingress Probe attached - ","Name: ":"cainelli.me-6c9d6b666-mcx9z","Namespace: ":"cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:228","msg":"Pod already has Egress Probe attached - ","Name: ":"cainelli.me-6c9d6b666-mcx9z","Namespace: ":"cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:228","msg":"AttacheBPFProbes for","pod":"cainelli.me-6c9d6b666-mcx9z"," in namespace":"cainelli"," with hostVethName":"enidc4c8256b73"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:146","msg":"Successfully attached required eBPF probes for","pod:":"cainelli.me-6c9d6b666-mcx9z","in namespace":"cainelli"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:263","msg":"Pod has an Ingress hook attached. Update the corresponding map","progFD: ":16,"mapName: ":"ingress_map"}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"L4 values: ","protocol: ":254,"startPort: ":0,"endPort: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"Current L4 entry count for catch all entry: ","count: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"Total L4 entry count for catch all entry: ","count: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"L4 values: ","protocol: ":254,"startPort: ":0,"endPort: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.592Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:421","msg":"ID of map to update: ","ID: ":25}
{"level":"info","ts":"2024-01-03T22:19:41.593Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:263","msg":"Pod has an Egress hook attached. Update the corresponding map","progFD: ":18,"mapName: ":"egress_map"}
{"level":"info","ts":"2024-01-03T22:19:41.593Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"L4 values: ","protocol: ":254,"startPort: ":0,"endPort: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.593Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"Current L4 entry count for catch all entry: ","count: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.593Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"Total L4 entry count for catch all entry: ","count: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.593Z","logger":"ebpf-client","caller":"ebpf/bpf_client.go:700","msg":"L4 values: ","protocol: ":254,"startPort: ":0,"endPort: ":0}
{"level":"info","ts":"2024-01-03T22:19:41.593Z","logger":"ebpf-client","caller":"controllers/policyendpoints_controller.go:421","msg":"ID of map to update: ","ID: ":26}
```

changed in [aws-network-policy-agent](https://github.com/aws/aws-network-policy-agent/blob/0fc3701810e7d2dc9b4c4613e341a83e78bcf88c/pkg/utils/utils.go#L75) to the following:

```go
func GetPodIdentifier(podName, podNamespace string) string {
	podName = strings.ReplaceAll(podName, ".", "_")
	podIdentifierPrefix := podName
	if strings.Contains(string(podName), "-") {
		tmpName := strings.Split(podName, "-")
		podIdentifierPrefix = strings.Join(tmpName[:len(tmpName)-1], "-")
	}
	return podIdentifierPrefix + "-" + podNamespace
}
```

I might have overlooked but I did not find a place where the other way around is needed.

**Comment by jayanthvn** [comment]
@cainelli - no problem at all. Yes it shouldn't crash but we need to bubble up the error about failed NP enforcement. We did think about a similar solution which you have here but still debating on the use case. Can you please share if you have any use case to have a dot? Since it is not recommended to have a "." in the name since it will interfere with DNS host names...

**Comment by cainelli** [comment]
tbh we really don't have a good reason for using `.` in pod names, it's an old naming convention mainly used in Jobs and we should move away from it. The main concern is how the aws-network-policy-agent will handle this. Since Kubernetes doesn't enforce the use of `.` in names, someone could easily get around NetworkPolicies.

**Comment by cainelli** [comment]
any update on this @jayanthvn? we're running with https://github.com/aws/aws-ebpf-sdk-go/pull/72 patch which would be great to see it upstream.

**Comment by jayanthvn** [comment]
Sorry for the delay on this. I have triggered tests on #72 and will review it.

I will get back regarding replacing dot(.) for your use case. Another option I was thinking to have unique hash..

**Comment by cainelli** [comment]
No worries, and thank you for getting back. Yes I also considered this option.

Out of curiosity, if I understood correctly pods from the same replicaset running in the same node share the same ebpf pin/map, can you tell the reasoning or give some references?

**Comment by jamhamblin** [comment]
We have also seen this issue replicated when using [Airflow](https://airflow.apache.org/) generating names with a `.` in that is outside our control. Would appreciate any help possible to get a fix upstream 🙏
